---
- name: Настройка Kubernetes кластера
  hosts: all
  become: yes
  tasks:
    - name: Отключение swap
      command: swapoff -a

    - name: Отключение swap при загрузке
      lineinfile:
        path: /etc/fstab
        regexp: '^.*swap.*$'
        state: absent

    - name: Настройка необходимых модулей
      command: modprobe {{ item }}
      loop:
        - overlay
        - br_netfilter

    - name: Настройка сети для Kubernetes
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

    - name: Применение системных настроек
      command: sysctl --system

- name: Инициализация кластера
  hosts: master
  become: yes
  tasks:
    - name: Инициализация кластера Kubernetes
      command: kubeadm init --control-plane-endpoint={{ master_ip }} --upload-certs
      register: kubeadm_init

    - name: Настройка kubectl
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        executable: /bin/bash

    - name: Установка сетевого плагина
      command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

    - name: Получение команды для присоединения рабочих узлов
      debug:
        msg: "{{ kubeadm_init.stdout_lines | select('search', 'kubeadm join') | list }}"

- name: Присоединение рабочих узлов к кластеру
  hosts: workers
  become: yes
  tasks:
    - name: Присоединение к кластеру
      command: "{{ join_command }}"
      when: join_command is defined

